# Generated by Django 3.0.8 on 2021-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(blank=True, default=True, max_length=100)),
                ('catagory', models.TextField(blank=True, default=True, max_length=100)),
            ],
        ),
    ]
