# Generated by Django 3.0.8 on 2021-08-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_auto_20210803_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to='files'),
        ),
    ]
