# Generated by Django 3.0.8 on 2021-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_auto_20210803_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
