# Generated by Django 3.0.8 on 2021-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0005_auto_20210803_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(default='', upload_to='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
